name: Tests
on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - uses: actions/checkout@v4
    - name: Build all
      run: |
        make
        ls -al ./out/c2w
        if ldd ./out/c2w ; then echo "must be static binary" ; exit 1 ; fi
        ls -al ./out/c2w-net
        if ldd ./out/c2w-net ; then echo "must be static binary" ; exit 1 ; fi

  test:
    runs-on: ubuntu-24.04
    name: Test
    strategy:
      fail-fast: false
      matrix:
        target: ["TestWasmtime", "TestWamr", "TestWasmer", "TestWazero", "TestWasmedge"]
        arch: ["x86_64", "(riscv64|aarch64)"]
    steps:
    - uses: actions/checkout@v4
    - name: binfmt
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install riscv64
    - name: test
      env:
        GO_TEST_FLAGS: -run ${{ matrix.target }}/.*arch=${{ matrix.arch }}.*
      run: |
        make test

  browser:
    runs-on: ubuntu-24.04
    name: BrowserTests
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64", "riscv64", "aarch64"]
    steps:
    - uses: actions/checkout@v4
    - name: test
      env:
        GO_TEST_FLAGS: -run TestBrowsers/.*arch=${{ matrix.arch }}.*
      run: |
        make test

  # benchmark:
  #   runs-on: ubuntu-24.04
  #   name: Benchmark
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Benchmark
  #     run: |
  #       make benchmark

  linter:
    runs-on: ubuntu-24.04
    name: Linter
    steps:
    - uses: actions/checkout@v4
    - name: validate vendor
      run: |
        make validate-vendor
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
        args: --verbose

  project:
    name: Project Checks
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - uses: actions/checkout@v4
      with:
        fetch-depth: 100
    - name: "Check DCO sign"
      run: |
        go install github.com/vbatts/git-validation@v1.2.0
        git-validation -v -run DCO
